# Generated by Django 3.0.5 on 2020-04-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ram_left',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ram_usage',
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_core',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_model',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='hostname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='kernal',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='os',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='os_arch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
