# Generated by Django 3.0.5 on 2020-04-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20200413_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='active_connections',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_load_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_load_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_load_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_speed',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='default_interface',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='file_descriptors_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='file_descriptors_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='file_descriptors_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='ping_latency',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='ram_buffer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='ram_caches',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='ram_free',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='ram_total',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='ram_usage',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_sessions',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='swap_free',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='swap_total',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='swap_usage',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='uptime',
            field=models.CharField(default='', max_length=50),
        ),
    ]
