# Generated by Django 3.0.5 on 2020-04-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_auto_20200414_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='all_interfaces',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='server',
            name='all_interfaces_current',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='server',
            name='ipv4_addresses',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='server',
            name='ipv6_addresses',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='server',
            name='ping_latency',
            field=models.CharField(default='', max_length=250),
        ),
    ]
