# Generated by Django 3.0.5 on 2020-04-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_auto_20200414_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='disks',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='server',
            name='disks_inodes',
            field=models.CharField(default='', max_length=250),
        ),
    ]
