# Generated by Django 3.0.5 on 2020-04-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0005_auto_20200414_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpu_info',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_info_current',
            field=models.CharField(default='', max_length=300),
        ),
    ]
