# Generated by Django 3.0.5 on 2020-04-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0006_auto_20200414_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='active_connections',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='all_interfaces',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='all_interfaces_current',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_info',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_info_current',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='default_interface',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='disks',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='disks_inodes',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='file_descriptors_1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='file_descriptors_2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='file_descriptors_3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='ipv4_addresses',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='ipv6_addresses',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='ping_latency',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='ssh_sessions',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='uptime',
            field=models.CharField(default='', max_length=500),
        ),
    ]
